/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AccountIndexImport } from './routes/account/index'
import { Route as ProductsProductIdImport } from './routes/products/$productId'
import { Route as PaymentSuccessfulImport } from './routes/payment/successful'
import { Route as CollectionsSoldoutImport } from './routes/collections/soldout'
import { Route as CollectionsAccessoriesImport } from './routes/collections/accessories'
import { Route as AccountUpdateInformationImport } from './routes/account/update-information'
import { Route as AccountRegisterImport } from './routes/account/register'

// Create Virtual Routes

const PolicyTermsConditionsLazyImport = createFileRoute(
  '/policy/terms-conditions',
)()
const PolicyShippingPolicyLazyImport = createFileRoute(
  '/policy/shipping-policy',
)()
const PolicyRefundPolicyLazyImport = createFileRoute('/policy/refund-policy')()
const PolicyPrivacyPolicyLazyImport = createFileRoute(
  '/policy/privacy-policy',
)()
const InfoAboutLazyImport = createFileRoute('/info/about')()
const InfoFAQLazyImport = createFileRoute('/info/FAQ')()
const CollectionsOldLazyImport = createFileRoute('/collections/old')()
const CollectionsNewLazyImport = createFileRoute('/collections/new')()
const CollectionsAllLazyImport = createFileRoute('/collections/all')()
const AccountUpdatePasswordLazyImport = createFileRoute(
  '/account/update-password',
)()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AccountIndexRoute = AccountIndexImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRoute,
} as any)

const PolicyTermsConditionsLazyRoute = PolicyTermsConditionsLazyImport.update({
  id: '/policy/terms-conditions',
  path: '/policy/terms-conditions',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/policy/terms-conditions.lazy').then((d) => d.Route),
)

const PolicyShippingPolicyLazyRoute = PolicyShippingPolicyLazyImport.update({
  id: '/policy/shipping-policy',
  path: '/policy/shipping-policy',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/policy/shipping-policy.lazy').then((d) => d.Route),
)

const PolicyRefundPolicyLazyRoute = PolicyRefundPolicyLazyImport.update({
  id: '/policy/refund-policy',
  path: '/policy/refund-policy',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/policy/refund-policy.lazy').then((d) => d.Route),
)

const PolicyPrivacyPolicyLazyRoute = PolicyPrivacyPolicyLazyImport.update({
  id: '/policy/privacy-policy',
  path: '/policy/privacy-policy',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/policy/privacy-policy.lazy').then((d) => d.Route),
)

const InfoAboutLazyRoute = InfoAboutLazyImport.update({
  id: '/info/about',
  path: '/info/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/info/about.lazy').then((d) => d.Route))

const InfoFAQLazyRoute = InfoFAQLazyImport.update({
  id: '/info/FAQ',
  path: '/info/FAQ',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/info/FAQ.lazy').then((d) => d.Route))

const CollectionsOldLazyRoute = CollectionsOldLazyImport.update({
  id: '/collections/old',
  path: '/collections/old',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/collections/old.lazy').then((d) => d.Route),
)

const CollectionsNewLazyRoute = CollectionsNewLazyImport.update({
  id: '/collections/new',
  path: '/collections/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/collections/new.lazy').then((d) => d.Route),
)

const CollectionsAllLazyRoute = CollectionsAllLazyImport.update({
  id: '/collections/all',
  path: '/collections/all',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/collections/all.lazy').then((d) => d.Route),
)

const AccountUpdatePasswordLazyRoute = AccountUpdatePasswordLazyImport.update({
  id: '/account/update-password',
  path: '/account/update-password',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/account/update-password.lazy').then((d) => d.Route),
)

const ProductsProductIdRoute = ProductsProductIdImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRoute,
} as any)

const PaymentSuccessfulRoute = PaymentSuccessfulImport.update({
  id: '/payment/successful',
  path: '/payment/successful',
  getParentRoute: () => rootRoute,
} as any)

const CollectionsSoldoutRoute = CollectionsSoldoutImport.update({
  id: '/collections/soldout',
  path: '/collections/soldout',
  getParentRoute: () => rootRoute,
} as any)

const CollectionsAccessoriesRoute = CollectionsAccessoriesImport.update({
  id: '/collections/accessories',
  path: '/collections/accessories',
  getParentRoute: () => rootRoute,
} as any)

const AccountUpdateInformationRoute = AccountUpdateInformationImport.update({
  id: '/account/update-information',
  path: '/account/update-information',
  getParentRoute: () => rootRoute,
} as any)

const AccountRegisterRoute = AccountRegisterImport.update({
  id: '/account/register',
  path: '/account/register',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/account/register': {
      id: '/account/register'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterImport
      parentRoute: typeof rootRoute
    }
    '/account/update-information': {
      id: '/account/update-information'
      path: '/account/update-information'
      fullPath: '/account/update-information'
      preLoaderRoute: typeof AccountUpdateInformationImport
      parentRoute: typeof rootRoute
    }
    '/collections/accessories': {
      id: '/collections/accessories'
      path: '/collections/accessories'
      fullPath: '/collections/accessories'
      preLoaderRoute: typeof CollectionsAccessoriesImport
      parentRoute: typeof rootRoute
    }
    '/collections/soldout': {
      id: '/collections/soldout'
      path: '/collections/soldout'
      fullPath: '/collections/soldout'
      preLoaderRoute: typeof CollectionsSoldoutImport
      parentRoute: typeof rootRoute
    }
    '/payment/successful': {
      id: '/payment/successful'
      path: '/payment/successful'
      fullPath: '/payment/successful'
      preLoaderRoute: typeof PaymentSuccessfulImport
      parentRoute: typeof rootRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdImport
      parentRoute: typeof rootRoute
    }
    '/account/update-password': {
      id: '/account/update-password'
      path: '/account/update-password'
      fullPath: '/account/update-password'
      preLoaderRoute: typeof AccountUpdatePasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/collections/all': {
      id: '/collections/all'
      path: '/collections/all'
      fullPath: '/collections/all'
      preLoaderRoute: typeof CollectionsAllLazyImport
      parentRoute: typeof rootRoute
    }
    '/collections/new': {
      id: '/collections/new'
      path: '/collections/new'
      fullPath: '/collections/new'
      preLoaderRoute: typeof CollectionsNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/collections/old': {
      id: '/collections/old'
      path: '/collections/old'
      fullPath: '/collections/old'
      preLoaderRoute: typeof CollectionsOldLazyImport
      parentRoute: typeof rootRoute
    }
    '/info/FAQ': {
      id: '/info/FAQ'
      path: '/info/FAQ'
      fullPath: '/info/FAQ'
      preLoaderRoute: typeof InfoFAQLazyImport
      parentRoute: typeof rootRoute
    }
    '/info/about': {
      id: '/info/about'
      path: '/info/about'
      fullPath: '/info/about'
      preLoaderRoute: typeof InfoAboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/policy/privacy-policy': {
      id: '/policy/privacy-policy'
      path: '/policy/privacy-policy'
      fullPath: '/policy/privacy-policy'
      preLoaderRoute: typeof PolicyPrivacyPolicyLazyImport
      parentRoute: typeof rootRoute
    }
    '/policy/refund-policy': {
      id: '/policy/refund-policy'
      path: '/policy/refund-policy'
      fullPath: '/policy/refund-policy'
      preLoaderRoute: typeof PolicyRefundPolicyLazyImport
      parentRoute: typeof rootRoute
    }
    '/policy/shipping-policy': {
      id: '/policy/shipping-policy'
      path: '/policy/shipping-policy'
      fullPath: '/policy/shipping-policy'
      preLoaderRoute: typeof PolicyShippingPolicyLazyImport
      parentRoute: typeof rootRoute
    }
    '/policy/terms-conditions': {
      id: '/policy/terms-conditions'
      path: '/policy/terms-conditions'
      fullPath: '/policy/terms-conditions'
      preLoaderRoute: typeof PolicyTermsConditionsLazyImport
      parentRoute: typeof rootRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/update-information': typeof AccountUpdateInformationRoute
  '/collections/accessories': typeof CollectionsAccessoriesRoute
  '/collections/soldout': typeof CollectionsSoldoutRoute
  '/payment/successful': typeof PaymentSuccessfulRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/account/update-password': typeof AccountUpdatePasswordLazyRoute
  '/collections/all': typeof CollectionsAllLazyRoute
  '/collections/new': typeof CollectionsNewLazyRoute
  '/collections/old': typeof CollectionsOldLazyRoute
  '/info/FAQ': typeof InfoFAQLazyRoute
  '/info/about': typeof InfoAboutLazyRoute
  '/policy/privacy-policy': typeof PolicyPrivacyPolicyLazyRoute
  '/policy/refund-policy': typeof PolicyRefundPolicyLazyRoute
  '/policy/shipping-policy': typeof PolicyShippingPolicyLazyRoute
  '/policy/terms-conditions': typeof PolicyTermsConditionsLazyRoute
  '/account': typeof AccountIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/update-information': typeof AccountUpdateInformationRoute
  '/collections/accessories': typeof CollectionsAccessoriesRoute
  '/collections/soldout': typeof CollectionsSoldoutRoute
  '/payment/successful': typeof PaymentSuccessfulRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/account/update-password': typeof AccountUpdatePasswordLazyRoute
  '/collections/all': typeof CollectionsAllLazyRoute
  '/collections/new': typeof CollectionsNewLazyRoute
  '/collections/old': typeof CollectionsOldLazyRoute
  '/info/FAQ': typeof InfoFAQLazyRoute
  '/info/about': typeof InfoAboutLazyRoute
  '/policy/privacy-policy': typeof PolicyPrivacyPolicyLazyRoute
  '/policy/refund-policy': typeof PolicyRefundPolicyLazyRoute
  '/policy/shipping-policy': typeof PolicyShippingPolicyLazyRoute
  '/policy/terms-conditions': typeof PolicyTermsConditionsLazyRoute
  '/account': typeof AccountIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/update-information': typeof AccountUpdateInformationRoute
  '/collections/accessories': typeof CollectionsAccessoriesRoute
  '/collections/soldout': typeof CollectionsSoldoutRoute
  '/payment/successful': typeof PaymentSuccessfulRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/account/update-password': typeof AccountUpdatePasswordLazyRoute
  '/collections/all': typeof CollectionsAllLazyRoute
  '/collections/new': typeof CollectionsNewLazyRoute
  '/collections/old': typeof CollectionsOldLazyRoute
  '/info/FAQ': typeof InfoFAQLazyRoute
  '/info/about': typeof InfoAboutLazyRoute
  '/policy/privacy-policy': typeof PolicyPrivacyPolicyLazyRoute
  '/policy/refund-policy': typeof PolicyRefundPolicyLazyRoute
  '/policy/shipping-policy': typeof PolicyShippingPolicyLazyRoute
  '/policy/terms-conditions': typeof PolicyTermsConditionsLazyRoute
  '/account/': typeof AccountIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/register'
    | '/account/update-information'
    | '/collections/accessories'
    | '/collections/soldout'
    | '/payment/successful'
    | '/products/$productId'
    | '/account/update-password'
    | '/collections/all'
    | '/collections/new'
    | '/collections/old'
    | '/info/FAQ'
    | '/info/about'
    | '/policy/privacy-policy'
    | '/policy/refund-policy'
    | '/policy/shipping-policy'
    | '/policy/terms-conditions'
    | '/account'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/register'
    | '/account/update-information'
    | '/collections/accessories'
    | '/collections/soldout'
    | '/payment/successful'
    | '/products/$productId'
    | '/account/update-password'
    | '/collections/all'
    | '/collections/new'
    | '/collections/old'
    | '/info/FAQ'
    | '/info/about'
    | '/policy/privacy-policy'
    | '/policy/refund-policy'
    | '/policy/shipping-policy'
    | '/policy/terms-conditions'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/account/register'
    | '/account/update-information'
    | '/collections/accessories'
    | '/collections/soldout'
    | '/payment/successful'
    | '/products/$productId'
    | '/account/update-password'
    | '/collections/all'
    | '/collections/new'
    | '/collections/old'
    | '/info/FAQ'
    | '/info/about'
    | '/policy/privacy-policy'
    | '/policy/refund-policy'
    | '/policy/shipping-policy'
    | '/policy/terms-conditions'
    | '/account/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountUpdateInformationRoute: typeof AccountUpdateInformationRoute
  CollectionsAccessoriesRoute: typeof CollectionsAccessoriesRoute
  CollectionsSoldoutRoute: typeof CollectionsSoldoutRoute
  PaymentSuccessfulRoute: typeof PaymentSuccessfulRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  AccountUpdatePasswordLazyRoute: typeof AccountUpdatePasswordLazyRoute
  CollectionsAllLazyRoute: typeof CollectionsAllLazyRoute
  CollectionsNewLazyRoute: typeof CollectionsNewLazyRoute
  CollectionsOldLazyRoute: typeof CollectionsOldLazyRoute
  InfoFAQLazyRoute: typeof InfoFAQLazyRoute
  InfoAboutLazyRoute: typeof InfoAboutLazyRoute
  PolicyPrivacyPolicyLazyRoute: typeof PolicyPrivacyPolicyLazyRoute
  PolicyRefundPolicyLazyRoute: typeof PolicyRefundPolicyLazyRoute
  PolicyShippingPolicyLazyRoute: typeof PolicyShippingPolicyLazyRoute
  PolicyTermsConditionsLazyRoute: typeof PolicyTermsConditionsLazyRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountUpdateInformationRoute: AccountUpdateInformationRoute,
  CollectionsAccessoriesRoute: CollectionsAccessoriesRoute,
  CollectionsSoldoutRoute: CollectionsSoldoutRoute,
  PaymentSuccessfulRoute: PaymentSuccessfulRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  AccountUpdatePasswordLazyRoute: AccountUpdatePasswordLazyRoute,
  CollectionsAllLazyRoute: CollectionsAllLazyRoute,
  CollectionsNewLazyRoute: CollectionsNewLazyRoute,
  CollectionsOldLazyRoute: CollectionsOldLazyRoute,
  InfoFAQLazyRoute: InfoFAQLazyRoute,
  InfoAboutLazyRoute: InfoAboutLazyRoute,
  PolicyPrivacyPolicyLazyRoute: PolicyPrivacyPolicyLazyRoute,
  PolicyRefundPolicyLazyRoute: PolicyRefundPolicyLazyRoute,
  PolicyShippingPolicyLazyRoute: PolicyShippingPolicyLazyRoute,
  PolicyTermsConditionsLazyRoute: PolicyTermsConditionsLazyRoute,
  AccountIndexRoute: AccountIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/account/register",
        "/account/update-information",
        "/collections/accessories",
        "/collections/soldout",
        "/payment/successful",
        "/products/$productId",
        "/account/update-password",
        "/collections/all",
        "/collections/new",
        "/collections/old",
        "/info/FAQ",
        "/info/about",
        "/policy/privacy-policy",
        "/policy/refund-policy",
        "/policy/shipping-policy",
        "/policy/terms-conditions",
        "/account/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/account/register": {
      "filePath": "account/register.tsx"
    },
    "/account/update-information": {
      "filePath": "account/update-information.tsx"
    },
    "/collections/accessories": {
      "filePath": "collections/accessories.tsx"
    },
    "/collections/soldout": {
      "filePath": "collections/soldout.tsx"
    },
    "/payment/successful": {
      "filePath": "payment/successful.tsx"
    },
    "/products/$productId": {
      "filePath": "products/$productId.tsx"
    },
    "/account/update-password": {
      "filePath": "account/update-password.lazy.tsx"
    },
    "/collections/all": {
      "filePath": "collections/all.lazy.tsx"
    },
    "/collections/new": {
      "filePath": "collections/new.lazy.tsx"
    },
    "/collections/old": {
      "filePath": "collections/old.lazy.tsx"
    },
    "/info/FAQ": {
      "filePath": "info/FAQ.lazy.tsx"
    },
    "/info/about": {
      "filePath": "info/about.lazy.tsx"
    },
    "/policy/privacy-policy": {
      "filePath": "policy/privacy-policy.lazy.tsx"
    },
    "/policy/refund-policy": {
      "filePath": "policy/refund-policy.lazy.tsx"
    },
    "/policy/shipping-policy": {
      "filePath": "policy/shipping-policy.lazy.tsx"
    },
    "/policy/terms-conditions": {
      "filePath": "policy/terms-conditions.lazy.tsx"
    },
    "/account/": {
      "filePath": "account/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
